---
all:
  hosts:
    remote:
      ansible_ssh_user: "{{ lookup('env', 'SSH_USER') }}"
      ansible_ssh_host: "{{ lookup('env', 'SERVER_IP') }}"
      ansible_ssh_private_key_file: /root/.ssh/id_rsa
      ansible_connection: ssh
      ansible_python_interpreter: /usr/bin/python3
