## docker-compose.yml for launch of Traefik, Watchtower and Portainer

##-- Notes ---------------------------------------------------------------------
## 02-May-2019  Restored Portainer's .env variables.
## 24-Apr-2019  Still working to make Traefik dashboard visible
## 24-Apr-2019  Adding more .env vars for Traefik and Portainer control
## 23-Apr-2019  Added Acme staging CA server spec.  Remove for production!
## 23-Apr-2019  Added portainer service
## 17-Apr-2019  --entrypoints="Name:https Address::443 TLS" line replaced with
##   new line in proxy:command to remove weak ciphers in Traefik.
##------------------------------------------------------------------------------

## Add the --acme.caserver... line back into 'command:' in order to use LE's Acme staging CA server for testing.
## Remove it for final production deployment.
#      --acme.caserver="https://acme-staging-v02.api.letsencrypt.org/directory" \

version: '3.2'

networks:
  webgateway:
    driver: bridge

services:

  proxy:
    container_name: traefik_proxy
    image: traefik
    command: >-
      --docker --logLevel=INFO \
      --acme \
      --acme.acmelogging \
      --acme.dnschallenge=false \
      --acme.entrypoint="https" \
      --acme.httpchallenge \
      --acme.httpChallenge.entryPoint="http" \
      --acme.onhostrule=true \
      --acme.storage="/root/acme.json" \
      --acme.email="${LE_EMAIL}" \
      --entrypoints="Name:http Address::80 Redirect.EntryPoint:https" \
      --entryPoints="Name:https Address::443 TLS TLS.MinVersion:VersionTLS12 TLS.CipherSuites:TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256" \
      --defaultentrypoints="http,https" \
      --api \
      --api.entryPoint="proxy" \
      --api.dashboard=true
## Trying to open traefik2.grinnell.edu so I can see the Traefik dashboard
#      --api.entryPoint="http://traefik2.grinnell.edu" \
#      --api.dashboard=true \
    labels:
      traefik.enable: true
      traefik.frontend.auth.basic: "admin:$$2y$$05$$pJEzHJBzfoYYS7/hGAedcOP8XdsqNXE7j.LHFBVjueASOqOvvjGOy"
      traefik.frontend.redirect.regex: "^(.*)/traefik$$"
      traefik.frontend.redirect.replacement: "$$1/traefik/"
      traefik.frontend.rule: "PathPrefix:/portainer;ReplacePathRegex: ^/traefik/(.*) /$$1"
      traefik.port: 8080
## More failed attempts to make the Traefik dashboard visible
#      - traefik.enable=true    ## we want to be able to see the Traefik dashboard!
#      - traefik.port=8080
#      - "traefik.frontend.rule=Host:traefik2.grinnell.edu"
#      - "traefik.frontend.auth.basic.users=admin:$$2y$$05$$pJEzHJBzfoYYS7/hGAedcOP8XdsqNXE7j.LHFBVjueASOqOvvjGOy"
    networks:
      - webgateway
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/null:/traefik.toml
      - /root/acme.json:/root/acme.json

  watchtower:
    container_name: watchtower
    image: v2tec/watchtower
    labels:
      - traefik.enable=false
      - label-enable=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  portainer:
    container_name: portainer
    image: portainer/portainer
    command: --admin-password ${PORTAINER_ADMIN_PASS} -H unix:///var/run/docker.sock
    networks:
      - webgateway
    ports:
      - "9000:9000"
      #- "9010:9000" ## Remap to avoid conflicts on systems/servers with portainer already running.
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
#      - portainer-data:/data

    ## traefik.frontend.... bits per
    ##   https://github.com/pascalandy/docker-stack-this/blob/master/traefik_stack5/toolportainer.yml#L55
    labels:
      traefik.port: 9000
      traefik.enable: true
      traefik.frontend.redirect.regex: "^(.*)/portainer$$"
      traefik.frontend.redirect.replacement: "$$1/portainer/"
      traefik.frontend.rule: "PathPrefix:/portainer;ReplacePathRegex: ^/portainer/(.*) /$$1"
